[server]
port = 8000
host = "127.0.0.1"

[github]
user_agent = "Glu"
organization = "dummy"
webhook_secret = "e12345678901234567890"
private_key = """
-----BEGIN RSA PRIVATE KEY-----
QWERTYUIOPASDFGHJKLZXCVBNM
QWERTYUIOPASDFGHJKLZXCVBNM
QWERTYUIOPASDFGHJKLZXCVBNM
-----END RSA PRIVATE KEY-----"""

[openai]
api_key = "sk-qwertyuiopasdfghjklzxcvbnm"


[slack]
api_token = "xoxb-qwertyuiopasdfghjklzxcvbnm"

[slack.automations.watch_user_created]
target_channel_id = "C0123456789" #axon-testing

[[slack.automations.watch_github_lables]]
github_label_name_or_id = "testproj"
target_channel_id = "C0123456789" #axon-testing

